<?php
$potions = [
    ["name" => "Potion of Healing",  "rarity" => "common", "value" => 10, "color" => "#FF0000"],
    ["name" => "Potion of Mana",  "rarity" => "rare", "value" => 50, "color" => "#0000FF"],
    ["name" => "Potion of Strength",  "rarity" => "epic", "value" => 150, "color" => "#FF6600"],
    ["name" => "Potion of Speed",  "rarity" => "rare", "value" => 75, "color" => "#00FF00"],
    ["name" => "Potion of Invisibility",  "rarity" => "legendary", "value" => 300, "color" => "#CCCCCC"],
    ["name" => "Potion of Fire Resistance",  "rarity" => "common", "value" => 20, "color" => "#FF4500"],
    ["name" => "Potion of Water Breathing",  "rarity" => "rare", "value" => 60, "color" => "#1E90FF"],
    ["name" => "Potion of Night Vision",  "rarity" => "common", "value" => 15, "color" => "#FFFF33"],
    ["name" => "Potion of Luck",  "rarity" => "epic", "value" => 200, "color" => "#FFD700"],
    ["name" => "Potion of Feather Falling",  "rarity" => "common", "value" => 12, "color" => "#F5DEB3"],
    ["name" => "Potion of Regeneration",  "rarity" => "rare", "value" => 80, "color" => "#FF69B4"],
    ["name" => "Potion of Poison",  "rarity" => "common", "value" => 5, "color" => "#006400"],
    ["name" => "Potion of Antidote",  "rarity" => "rare", "value" => 55, "color" => "#98FB98"],
    ["name" => "Potion of Courage",  "rarity" => "epic", "value" => 175, "color" => "#FF6347"],
    ["name" => "Potion of Wisdom",  "rarity" => "legendary", "value" => 400, "color" => "#8A2BE2"],
    ["name" => "Potion of Stone Skin",  "rarity" => "rare", "value" => 90, "color" => "#A9A9A9"],
    ["name" => "Potion of Energy",  "rarity" => "common", "value" => 18, "color" => "#FF8C00"],
    ["name" => "Potion of Clairvoyance",  "rarity" => "epic", "value" => 220, "color" => "#9370DB"],
    ["name" => "Potion of Frost Resistance",  "rarity" => "common", "value" => 25, "color" => "#ADD8E6"],
    ["name" => "Potion of Fireball",  "rarity" => "epic", "value" => 250, "color" => "#FF4500"],
    ["name" => "Potion of Transformation",  "rarity" => "legendary", "value" => 500, "color" => "#9400D3"],
    ["name" => "Potion of Lightning",  "rarity" => "rare", "value" => 95, "color" => "#FFD700"],
    ["name" => "Potion of Charm",  "rarity" => "rare", "value" => 70, "color" => "#FFB6C1"],
    ["name" => "Potion of Shadow",  "rarity" => "epic", "value" => 190, "color" => "#2F4F4F"],
    ["name" => "Potion of Bloodlust",  "rarity" => "epic", "value" => 240, "color" => "#8B0000"],
    ["name" => "Potion of Eternal Youth",  "rarity" => "legendary", "value" => 1000, "color" => "#FFE4B5"],
    ["name" => "Potion of Fire",  "rarity" => "rare", "value" => 110, "color" => "#FF6347"],
    ["name" => "Potion of Mind Control",  "rarity" => "legendary", "value" => 600, "color" => "#4B0082"],
    ["name" => "Potion of Dreams",  "rarity" => "common", "value" => 14, "color" => "#FF1493"],
    ["name" => "Potion of Stamina",  "rarity" => "rare", "value" => 85, "color" => "#32CD32"],
    ["name" => "Potion of Rage",  "rarity" => "epic", "value" => 210, "color" => "#B22222"],
    ["name" => "Potion of Purity",  "rarity" => "common", "value" => 11, "color" => "#FFFACD"],
    ["name" => "Potion of Harmony",  "rarity" => "rare", "value" => 65, "color" => "#00CED1"],
    ["name" => "Potion of Dragon's Breath",  "rarity" => "legendary", "value" => 700, "color" => "#FF4500"],
    ["name" => "Potion of Fortune",  "rarity" => "rare", "value" => 120, "color" => "#FFD700"],
    ["name" => "Potion of Love",  "rarity" => "epic", "value" => 180, "color" => "#FF69B4"],
    ["name" => "Potion of the Sun",  "rarity" => "epic", "value" => 195, "color" => "#FFD700"],
    ["name" => "Potion of the Moon",  "rarity" => "rare", "value" => 105, "color" => "#87CEEB"],
    ["name" => "Potion of Phantom",  "rarity" => "legendary", "value" => 550, "color" => "#2E2E2E"],
];
