const wizards = [
  {
    name: "Alaric Shadowveil",
    xp: 1200,
    age: 140,
    birthplace: "Mistwood Forest",
    spells: ["Shadow Cloak", "Ethereal Chains", "Spectral Shards"],
  },
  {
    name: "Brynn Starflare",
    xp: 850,
    age: 95,
    birthplace: "Skylight Citadel",
    spells: ["Meteor Swarm", "Luminous Surge", "Astral Shield"],
  },
  {
    name: "Caelum Frostwind",
    xp: 2300,
    age: 200,
    birthplace: "Frozen Peaks",
    spells: ["Ice Lance", "Frost Barrier", "Glacial Blast", "Snowfall Grace"],
  },
  {
    name: "Daria Emberforge",
    xp: 1700,
    age: 130,
    birthplace: "Molten Spire",
    spells: ["Flame Whip", "Molten Armor", "Inferno Burst", "Fireball"],
  },
  {
    name: "Elyra Moonshadow",
    xp: 950,
    age: 100,
    birthplace: "Silverlake",
    spells: ["Lunar Beam", "Dreamwalk", "Moonlit Shield"],
  },
  {
    name: "Faelith Stormcaller",
    xp: 1800,
    age: 150,
    birthplace: "Thundermount",
    spells: ["Lightning Bolt", "Storm Surge", "Thunderclap"],
  },
  {
    name: "Gareth Ironbark",
    xp: 1200,
    age: 140,
    birthplace: "Eldertree Grove",
    spells: ["Barkskin", "Earthquake", "Root Snare"],
  },
  {
    name: "Helena Sunblaze",
    xp: 2500,
    age: 210,
    birthplace: "Golden Sands",
    spells: ["Solar Flare", "Radiant Shield", "Blinding Light"],
  },
  {
    name: "Icarus Windwhisper",
    xp: 400,
    age: 60,
    birthplace: "Zephyr Cove",
    spells: ["Air Slash", "Wind Gust", "Featherfall"],
  },
  {
    name: "Jorik Blackthorn",
    xp: 1450,
    age: 125,
    birthplace: "Shadowmoor",
    spells: ["Dark Tendrils", "Soul Drain", "Voidstep"],
  },
  {
    name: "Kaida Flameheart",
    xp: 600,
    age: 70,
    birthplace: "Crimson Isle",
    spells: ["Ember Spark", "Blaze Step", "Scorch Wave"],
  },
  {
    name: "Lysandra Greenweaver",
    xp: 1900,
    age: 160,
    birthplace: "Emerald Glade",
    spells: ["Nature's Grasp", "Vine Lash", "Verdant Pulse"],
  },
  {
    name: "Marek Ironshield",
    xp: 3000,
    age: 250,
    birthplace: "Fort Granite",
    spells: ["Iron Wall", "Stone Fist", "Earthen Armor", "Seismic Stomp"],
  },
  {
    name: "Nerissa Tidebringer",
    xp: 1350,
    age: 120,
    birthplace: "Azure Bay",
    spells: ["Water Jet", "Tidal Wave", "Aqua Barrier"],
  },
  {
    name: "Orin Ashenvale",
    xp: 2200,
    age: 190,
    birthplace: "Cinder Hollow",
    spells: ["Flame Arc", "Burning Barrage", "Ashen Veil"],
  },
  {
    name: "Persephone Nightshade",
    xp: 1100,
    age: 110,
    birthplace: "Duskmire",
    spells: ["Nightfall", "Shadowbind", "Specter Strike"],
  },
  {
    name: "Quentin Brightspark",
    xp: 500,
    age: 65,
    birthplace: "Radiant Meadow",
    spells: ["Light Ray", "Beacon Pulse", "Dazzling Shield"],
  },
  {
    name: "Rhiannon Starweaver",
    xp: 1600,
    age: 140,
    birthplace: "Celestial Spire",
    spells: ["Starfall", "Cosmic Ray", "Nebula Shield"],
  },
  {
    name: "Soren Windstride",
    xp: 1300,
    age: 120,
    birthplace: "Gale Summit",
    spells: ["Gust Wall", "Aero Blade", "Cyclone Dance"],
  },
  {
    name: "Thalric Grimshade",
    xp: 2700,
    age: 220,
    birthplace: "Ebon Hollow",
    spells: ["Wraith Bolt", "Phantom Slash", "Shadow Cloak"],
  },
  {
    name: "Ulrich Dragonspire",
    xp: 2000,
    age: 180,
    birthplace: "Dragon's Roost",
    spells: ["Firestorm", "Dragon's Roar", "Infernal Claws"],
  },
  {
    name: "Vanya Frostveil",
    xp: 1400,
    age: 130,
    birthplace: "Snowmyst Vale",
    spells: ["Ice Nova", "Crystal Shield", "Arctic Burst"],
  },
  {
    name: "Yennefer of Vengerberg",
    xp: 3200,
    age: 220,
    birthplace: "Vengerberg",
    spells: ["Portal Strike", "Chaos Surge", "Time Warp"],
  },
  {
    name: "Albus Dumbledore",
    xp: 5000,
    age: 150,
    birthplace: "Godric's Hollow",
    spells: ["Elder Wand Mastery", "Fawkes' Flame", "Invisibility Shield"],
  },
  {
    name: "Gandalf the Grey",
    xp: 8000,
    age: 1100,
    birthplace: "Valinor",
    spells: ["Light of Eärendil", "Flame of Anor", "Stormcaller"],
  },
  {
    name: "Merlin Ambrosius",
    xp: 10000,
    age: 1200,
    birthplace: "Camelot",
    spells: ["Mystic Barrier", "Timeweave", "Dragon Summon"],
  },
  {
    name: "Saruman the White",
    xp: 7500,
    age: 1100,
    birthplace: "Orthanc",
    spells: ["Voice of Command", "Power Burst", "Dark Corruption"],
  },
  {
    name: "Morgana Le Fay",
    xp: 4000,
    age: 500,
    birthplace: "Avalon",
    spells: ["Dark Enchantment", "Illusion Cloak", "Dreambinding"],
  },
  {
    name: "Rand al'Thor",
    xp: 3500,
    age: 23,
    birthplace: "Two Rivers",
    spells: ["Call of the Dragon", "Flame of Tar Valon", "Wheel of Time"],
  },
  {
    name: "Doctor Strange",
    xp: 4500,
    age: 42,
    birthplace: "New York City",
    spells: ["Mirror Dimension", "Sling Ring Portal", "Eye of Agamotto"],
  },
  {
    name: "Elminster Aumar",
    xp: 9000,
    age: 1000,
    birthplace: "Shadowdale",
    spells: ["Silver Fire", "Spellstorm", "Divine Intervention"],
  },
  {
    name: "Raistlin Majere",
    xp: 6000,
    age: 45,
    birthplace: "Solace",
    spells: ["Hourglass Eyes", "Soul Devour", "Dark Horizon"],
  },
  {
    name: "Harry Potter",
    xp: 2000,
    age: 21,
    birthplace: "Godric's Hollow",
    spells: ["Expelliarmus", "Stupefy", "Patronus Charm"],
  },
  {
    name: "Hermione Granger",
    xp: 2200,
    age: 21,
    birthplace: "London",
    spells: ["Petrificus Totalus", "Obliviate", "Protego Maxima"],
  },
  {
    name: "Sabrina Spellman",
    xp: 3000,
    age: 18,
    birthplace: "Greendale",
    spells: ["Necromancy Whisper", "Astral Projection", "Witch's Hex"],
  },
  {
    name: "Prospero Tempest",
    xp: 7000,
    age: 60,
    birthplace: "Isle of Enchantment",
    spells: ["Tempest Fury", "Spirit Control", "Illusion Mirage"],
  },
  {
    name: "Rincewind the Wizzard",
    xp: 1500,
    age: 45,
    birthplace: "Unseen University",
    spells: ["Luggage Summon", "Spell of Improbability", "Flee Mastery"],
  },
  {
    name: "Newt Scamander",
    xp: 2400,
    age: 40,
    birthplace: "Hufflepuff Manor",
    spells: ["Beast Whisper", "Containment Charm", "Calming Hex"],
  },
  {
    name: "Glinda the Good Witch",
    xp: 5000,
    age: 300,
    birthplace: "Emerald City",
    spells: ["Bubble Travel", "Kindness Charm", "Emerald Ray"],
  },
  {
    name: "The Wicked Witch of the West",
    xp: 4800,
    age: 350,
    birthplace: "West Oz",
    spells: ["Flying Monkeys", "Melting Curse", "Black Flame"],
  },
];
